import 'drawer_item.dart';

class DrawerList {
  List<DrawerItem> items = [
    DrawerItem("تقديم", 5),
    DrawerItem("مدخل", 7),
    DrawerItem("أبو بكر الصديق", 13),
    DrawerItem("محمد بن عبدالكريم الخطابي", 17),
    DrawerItem("السيدة هاجر", 23),
    DrawerItem("عمر بن العاص", 26),
    DrawerItem("النجاشي", 31),
    DrawerItem("الصحابة", 34),
    DrawerItem("البدريون", 39),
    DrawerItem("الزبير بن العوام", 42),
    DrawerItem("طلحة بن عبيدالله", 45),
    DrawerItem("سليم الاول", 47),
    DrawerItem("الاخوان بربوسا", 52),
    DrawerItem("سليمان القانوني", 60),
    DrawerItem("سليمان الحلبي", 63),
    DrawerItem("الامير عبدالقادر الجزائري", 67),
    DrawerItem("عبدالحميد بن باديس", 72),
    DrawerItem("البربر الامازيغ", 75),
    DrawerItem("طارق بن زياد", 78),
    DrawerItem("موسي بن نصير", 83),
    DrawerItem("خالد بن الوليد", 86),
    DrawerItem("ابو عبيدة بن الجراح", 92),
    DrawerItem("الغلام المجهول", 95),
    DrawerItem("عكرمة بن ابي جهل", 98),
    DrawerItem("أبو سفيان بن حرب", 101),
    DrawerItem("صغاطر", 104),
    DrawerItem("عبدالله المايوركي", 110),
    DrawerItem("سليمان الفارسي", 118),
    DrawerItem("آريوس", 123),
    DrawerItem("عمر المختار", 129),
    DrawerItem("عمر بن الخطاب", 134),
    DrawerItem("زيد بن عمر", 135),
    DrawerItem("سعيد بن زيد", 138),
    DrawerItem("زيد بن الخطاب", 141),
    DrawerItem("محمد بن عبدالوهاب", 147),
    DrawerItem("عبدالله بن ياسين", 153),
    DrawerItem("أبو بكر بن عمر اللٌنتوني", 156),
    DrawerItem("المتوكل بن الافطس", 159),
    DrawerItem("يوسف بن تاشفين", 164),
    DrawerItem("عبدالرحمن الناصر", 169),
    DrawerItem("بنو أمية", 173),
    DrawerItem("عثمان بن عفان", 176),
    DrawerItem("معاوية بن ابي سفيان", 189),
    DrawerItem("علي بن ابي طالب", 196),
    DrawerItem("الحسن بن علي", 204),
    DrawerItem("يزيد بن معاوية", 210),
    DrawerItem("ابو أيوب الانصاري", 217),
    DrawerItem("محمد الفاتح", 220),
    DrawerItem("مراد الثاني", 225),
    DrawerItem("فاطمة بنت محمد", 228),
    DrawerItem("خديجة بنت خويلد", 231),
    DrawerItem("عائشة ام المؤمنين", 234),
    DrawerItem("مريم", 242),
    DrawerItem("ام موسي", 245),
    DrawerItem("آسية بنت مزاحم", 248),
    DrawerItem("ماشطة بنت فرعون", 251),
    DrawerItem("مورس بوكاي", 254),
    DrawerItem("علي الجرجاوي", 258),
    DrawerItem("سيف الدين قطز", 261),
    DrawerItem("العز بن عبدالسلام", 267),
    DrawerItem("احمد بن تيمية", 270),
    DrawerItem("ثابت بن قرة", 273),
    DrawerItem("عباس بن فرناس", 278),
    DrawerItem("بيري رئيس", 280),
    DrawerItem("الهنود الحمر", 283),
    DrawerItem("زومبي", 291),
    DrawerItem("لابو لابو", 293),
    DrawerItem("عبدالرحمن إبراهيم بن سوري", 295),
    DrawerItem("مالكوم إكس", 298),
    DrawerItem("أبراهام لينكولن", 305),
    DrawerItem("محمد بن أمية", 303),
    DrawerItem("ابو يوسف يعقوب المنصور الماريني", 311),
    DrawerItem("ابو يوسف يعقوب المنصور الموحدي", 314),
    DrawerItem("صلاح الدين الايوبي", 317),
    DrawerItem("نور الدين زنكي", 322),
    DrawerItem("مؤمنو الفرس", 325),
    DrawerItem("البخاري", 328),
    DrawerItem("محمد ناصر الدين الالباني", 331),
    DrawerItem("ابو هريرة", 333),
    DrawerItem("الإمام الشوكاني", 337),
    DrawerItem("الانصار", 340),
    DrawerItem("محمد بن مسلمة", 345),
    DrawerItem("سعد بن ابي وقاص", 348),
    DrawerItem("اسود القادسية", 354),
    DrawerItem("العرب", 364),
    DrawerItem("زهير بن ابي سلمي", 371),
    DrawerItem("شعراء الرسول", 377),
    DrawerItem("الفرسان الثلاثة", 380),
    DrawerItem("العبادلة الاربعة", 383),
    DrawerItem("هارون الرشيد", 389),
    DrawerItem("احمد بن فضلان", 397),
    DrawerItem("اورانج زايب عالم قير", 405),
    DrawerItem("مجمد علي جناح", 410),
    DrawerItem("احمد ديدات", 413),
    DrawerItem("المخلََفون الثلاثة", 419),
    DrawerItem("عبدالرحمن بن عوف", 425),
    DrawerItem("عبدالعزيز الثعالبي", 428),
    DrawerItem("عز الدين القسَام", 432),
    DrawerItem("عبدالحميد الثاني", 445),
    DrawerItem("العثمانيون الجدد", 442),
    DrawerItem("جيل الصحوة", 447),
    DrawerItem("العظيم المائة", 451),
    DrawerItem("المراجع", 457),
    DrawerItem("فهرس الكتاب", 461),
  ];
}
